// AUTO-GENERATED by scripts/gen-modules.mjs from modules/*/package.json. Do not edit by hand.
import type { ModuleManifest } from "@hive/module-sdk";
import type { RendererModule } from "@hive/module-sdk/renderer";

/** Metadata of every module in the repo (enabled or not). */
export const MODULE_MANIFESTS: readonly ModuleManifest[] = [
  {
    "id": "library",
    "title": "Skills & Agents Library",
    "description": "Browse, inspect, and configure your coding agent skills, system prompts, and custom subagents with a dedicated editor.",
    "tier": "bonus",
    "icon": "blocks",
    "category": "Agent",
    "contributes": {
      "tabKinds": [
        "library"
      ],
      "commands": [
        {
          "id": "view.library",
          "title": "Open Skills & Agents",
          "category": "View",
          "keys": [
            "Mod+Shift+K"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "marketplace",
    "title": "Marketplace",
    "description": "Browse and discover MCP servers, Pi extensions, and agent skills from npm, Anthropic, and the official MCP registry.",
    "tier": "bonus",
    "icon": "shopping-bag",
    "category": "Workbench",
    "contributes": {
      "rightPanels": [
        "marketplace"
      ],
      "commands": [
        {
          "id": "view.marketplace",
          "title": "Toggle Marketplace Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "plan-previewer",
    "title": "Plan Previewer",
    "description": "Review agent plans in a rich tab: decisions, questions, annotations and approve / request changes. Runs a local server on :3456 for the plan-previewer CLI and installs its Pi skills.",
    "tier": "recommended",
    "icon": "clipboard-check",
    "category": "Agent",
    "agent": {
      "skills": [
        "agent/skills/*"
      ],
      "agentsMd": "agent/AGENTS.block.md",
      "bin": {
        "plan-previewer": "bin/plan-previewer.js"
      }
    },
    "contributes": {
      "tabKinds": [
        "plan"
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  }
];

/** Lazy entry points; only called for enabled modules. */
export const RENDERER_MODULE_LOADERS: Readonly<Record<string, () => Promise<{ default: RendererModule }>>> = {
  "library": () => import("@hive-module/library/renderer"),
  "marketplace": () => import("@hive-module/marketplace/renderer"),
  "plan-previewer": () => import("@hive-module/plan-previewer/renderer"),
};
