// AUTO-GENERATED by scripts/gen-modules.mjs from modules/*/package.json. Do not edit by hand.
import type { ModuleManifest } from "@hive/module-sdk";
import type { RendererModule } from "@hive/module-sdk/renderer";

/** Metadata of every module in the repo (enabled or not). */
export const MODULE_MANIFESTS: readonly ModuleManifest[] = [
  {
    "id": "plan-previewer",
    "title": "Plan Previewer",
    "description": "Review agent plans in a rich tab: decisions, questions, annotations and approve / request changes. Runs a local server on :3456 for the plan-previewer CLI and installs its Pi skills.",
    "tier": "recommended",
    "icon": "clipboard-check",
    "category": "Agent",
    "agent": {
      "skills": [
        "agent/skills/*"
      ],
      "agentsMd": "agent/AGENTS.block.md",
      "bin": {
        "plan-previewer": "bin/plan-previewer.js"
      }
    },
    "contributes": {
      "tabKinds": [
        "plan"
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  }
];

/** Lazy entry points; only called for enabled modules. */
export const RENDERER_MODULE_LOADERS: Readonly<Record<string, () => Promise<{ default: RendererModule }>>> = {
  "plan-previewer": () => import("@hive-module/plan-previewer/renderer"),
};
