#!/usr/bin/env node
/**
 * Module codegen. Scans `modules/<id>/package.json` ("hive" manifest block) and writes:
 *   apps/desktop/src/main/modules.generated.ts      manifest index + lazy import() of each src/main.ts
 *   apps/desktop/src/renderer/modules.generated.ts  manifest index + lazy import() of each src/renderer.tsx
 *
 * The manifest index is always bundled (metadata only) so core can list, explain and offer disabled modules.
 * Module code is only imported when the module is enabled. The generated files are committed; `--check`
 * fails (exit 1) when they are stale, which CI / the boundary check use.
 *
 * Usage: node scripts/gen-modules.mjs [--check]
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ID_RE = /^[a-z][a-z0-9-]*$/;
const TIERS = ["core", "recommended", "bonus"];

/** Reads and validates every module under `<root>/modules`. Throws with all problems at once. */
export function scanModules(root = ROOT) {
  const dir = join(root, "modules");
  if (!existsSync(dir)) return [];
  const errors = [];
  const modules = [];
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    if (!entry.isDirectory()) continue;
    const pkgPath = join(dir, entry.name, "package.json");
    if (!existsSync(pkgPath)) continue;
    let pkg;
    try {
      pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
    } catch (err) {
      errors.push(`${entry.name}: package.json is not valid JSON (${err.message})`);
      continue;
    }
    const m = pkg.hive;
    if (!m || typeof m !== "object") {
      errors.push(`${entry.name}: package.json has no "hive" manifest block`);
      continue;
    }
    if (m.id !== entry.name) errors.push(`${entry.name}: hive.id must equal the folder name (got ${JSON.stringify(m.id)})`);
    if (typeof m.id !== "string" || !ID_RE.test(m.id)) errors.push(`${entry.name}: invalid id`);
    if (pkg.name !== `@hive-module/${entry.name}`) errors.push(`${entry.name}: package name must be "@hive-module/${entry.name}"`);
    if (typeof m.title !== "string" || !m.title) errors.push(`${entry.name}: title is required`);
    if (typeof m.description !== "string") errors.push(`${entry.name}: description is required`);
    if (!TIERS.includes(m.tier)) errors.push(`${entry.name}: tier must be one of ${TIERS.join(", ")}`);
    const hasMain = existsSync(join(dir, entry.name, "src", "main.ts"));
    const hasRenderer = existsSync(join(dir, entry.name, "src", "renderer.tsx"));
    if (hasMain && pkg.exports?.["./main"] !== "./src/main.ts") errors.push(`${entry.name}: exports["./main"] must be "./src/main.ts"`);
    if (hasRenderer && pkg.exports?.["./renderer"] !== "./src/renderer.tsx")
      errors.push(`${entry.name}: exports["./renderer"] must be "./src/renderer.tsx"`);
    modules.push({ ...m, hasMain, hasRenderer });
  }

  const ids = new Set(modules.map((m) => m.id));
  const owners = new Map();
  for (const m of modules) {
    for (const dep of m.requires ?? []) if (!ids.has(dep)) errors.push(`${m.id}: requires unknown module "${dep}"`);
    const c = m.contributes ?? {};
    const claims = [
      ...(c.leftPanels ?? []).map((x) => `panel:${x}`),
      ...(c.rightPanels ?? []).map((x) => `panel:${x}`),
      ...(c.tabKinds ?? []).map((x) => `tab:${x}`),
      ...(c.commands ?? []).map((x) => `command:${x.id}`),
    ];
    for (const claim of claims) {
      if (owners.has(claim)) errors.push(`${m.id}: ${claim} is already declared by ${owners.get(claim)}`);
      else owners.set(claim, m.id);
    }
  }
  const cycle = findCycle(modules);
  if (cycle) errors.push(`dependency cycle: ${cycle.join(" -> ")}`);
  if (errors.length) throw new Error(`Invalid modules:\n  ${errors.join("\n  ")}`);
  return modules;
}

function findCycle(modules) {
  const byId = new Map(modules.map((m) => [m.id, m]));
  const state = new Map();
  const stack = [];
  let found = null;
  const visit = (id) => {
    if (found) return;
    if (state.get(id) === "done") return;
    if (state.get(id) === "visiting") {
      found = [...stack.slice(stack.indexOf(id)), id];
      return;
    }
    state.set(id, "visiting");
    stack.push(id);
    for (const dep of byId.get(id)?.requires ?? []) if (byId.has(dep)) visit(dep);
    stack.pop();
    state.set(id, "done");
  };
  for (const m of modules) visit(m.id);
  return found;
}

const HEADER = "// AUTO-GENERATED by scripts/gen-modules.mjs from modules/*/package.json. Do not edit by hand.\n";

function render(modules, side) {
  const isMain = side === "main";
  const flag = isMain ? "hasMain" : "hasRenderer";
  const typeName = isMain ? "MainModule" : "RendererModule";
  const loaders = modules
    .filter((m) => m[flag])
    .map((m) => `  ${JSON.stringify(m.id)}: () => import(${JSON.stringify(`@hive-module/${m.id}/${side}`)}),`)
    .join("\n");
  return (
    HEADER +
    `import type { ModuleManifest } from "@hive/module-sdk";\n` +
    `import type { ${typeName} } from "@hive/module-sdk/${side}";\n\n` +
    `/** Metadata of every module in the repo (enabled or not). */\n` +
    `export const MODULE_MANIFESTS: readonly ModuleManifest[] = ${JSON.stringify(modules, null, 2)};\n\n` +
    `/** Lazy entry points; only called for enabled modules. */\n` +
    `export const ${isMain ? "MAIN" : "RENDERER"}_MODULE_LOADERS: Readonly<Record<string, () => Promise<{ default: ${typeName} }>>> = {\n` +
    (loaders ? `${loaders}\n` : "") +
    `};\n`
  );
}

export const renderMain = (modules) => render(modules, "main");
export const renderRenderer = (modules) => render(modules, "renderer");

export function outputs(root = ROOT) {
  const modules = scanModules(root);
  return [
    [join(root, "apps/desktop/src/main/modules.generated.ts"), renderMain(modules)],
    [join(root, "apps/desktop/src/renderer/modules.generated.ts"), renderRenderer(modules)],
  ];
}

const norm = (s) => s.replace(/\r\n/g, "\n");

function main() {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [file, content] of outputs()) {
    const current = existsSync(file) ? readFileSync(file, "utf8") : null;
    if (current !== null && norm(current) === content) continue;
    if (check) {
      console.error(`[gen-modules] ${file} is out of date. Run: node scripts/gen-modules.mjs`);
      stale++;
    } else {
      writeFileSync(file, content, "utf8");
      console.log(`[gen-modules] wrote ${file}`);
    }
  }
  if (stale) process.exit(1);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    main();
  } catch (err) {
    console.error(`[gen-modules] ${err.message}`);
    process.exit(1);
  }
}
