// AUTO-GENERATED by scripts/gen-modules.mjs from modules/*/package.json. Do not edit by hand.
import type { ModuleManifest } from "@hive/module-sdk";
import type { MainModule } from "@hive/module-sdk/main";

/** Metadata of every module in the repo (enabled or not). */
export const MODULE_MANIFESTS: readonly ModuleManifest[] = [
  {
    "id": "actions",
    "title": "GitHub Actions",
    "description": "See queued, running and past GitHub Actions runs for the active project's repo, with jobs and steps, like the Actions tab on github.com.",
    "tier": "bonus",
    "icon": "play-circle",
    "category": "Workbench",
    "requires": [
      "git"
    ],
    "contributes": {
      "leftPanels": [
        "actions"
      ],
      "commands": [
        {
          "id": "view.actions",
          "title": "Toggle GitHub Actions Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "analytics",
    "title": "Usage & Cost Analytics",
    "description": "Comprehensive spend velocity, token telemetry, cost breakdown by model/project/day, and AI-driven efficiency analysis.",
    "tier": "bonus",
    "icon": "bar-chart-3",
    "category": "Insights",
    "contributes": {
      "tabKinds": [
        "usage"
      ],
      "commands": [
        {
          "id": "view.usage",
          "title": "Open Usage Analytics",
          "category": "View",
          "keys": [
            "Mod+Shift+U"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "bash-guard",
    "title": "Bash Guard",
    "description": "Intercepts potentially dangerous bash commands (rm -rf, git reset --hard, disk operations, sudo) and prompts for confirmation with an inline approval card above the composer.",
    "tier": "bonus",
    "recommended": true,
    "icon": "shield-alert",
    "category": "Security",
    "agent": {
      "extensions": [
        "agent/extensions/bash-guard.ts"
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "branches",
    "title": "Branches & History",
    "description": "Browse local and remote branches, check out, create and delete them, and explore the commit graph.",
    "tier": "bonus",
    "icon": "git-branch",
    "category": "Workbench",
    "requires": [
      "git"
    ],
    "contributes": {
      "leftPanels": [
        "branches"
      ],
      "commands": [
        {
          "id": "view.branches",
          "title": "Toggle Branches Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": false,
    "hasRenderer": true
  },
  {
    "id": "browser",
    "title": "Hive Browser",
    "description": "Integrated Chromium web browser with automatic background tab hibernation (RAM Saver) and web search.",
    "tier": "bonus",
    "icon": "globe",
    "category": "Workbench",
    "contributes": {
      "tabKinds": [
        "browser"
      ],
      "commands": [
        {
          "id": "browser.new",
          "title": "New Browser Tab",
          "category": "Browser",
          "keys": [
            "Mod+Shift+B"
          ]
        },
        {
          "id": "settings.browser",
          "title": "Settings: Browser & RAM",
          "category": "App"
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "context-breakdown",
    "title": "Context Window Breakdown",
    "description": "Token usage inspector showing exact model-reported and estimated tokens across instructions, tools, skills and conversation turns.",
    "tier": "bonus",
    "icon": "pie-chart",
    "category": "Workbench",
    "contributes": {
      "rightPanels": [
        "context"
      ],
      "commands": [
        {
          "id": "view.context",
          "title": "Toggle Context Window Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": false,
    "hasRenderer": true
  },
  {
    "id": "diff-viewer",
    "title": "File & Diff Viewer",
    "description": "Open files and diffs as tabs: highlighted source, rendered Markdown/JSON/HTML/SVG previews, and a line-by-line diff view with Ask Pi.",
    "tier": "recommended",
    "icon": "file-diff",
    "category": "Editor",
    "contributes": {
      "tabKinds": [
        "file",
        "diff"
      ],
      "commands": [
        {
          "id": "file.open",
          "title": "Open File in Viewer",
          "category": "File"
        }
      ]
    },
    "hasMain": false,
    "hasRenderer": true
  },
  {
    "id": "files",
    "title": "Files",
    "description": "Browse the project file tree, open files in the viewer and run scripts in the terminal.",
    "tier": "recommended",
    "icon": "files",
    "category": "Workbench",
    "requires": [
      "diff-viewer"
    ],
    "optionalDeps": [
      "terminal",
      "git"
    ],
    "contributes": {
      "leftPanels": [
        "files"
      ],
      "commands": [
        {
          "id": "view.files",
          "title": "Toggle Files Panel",
          "category": "View",
          "keys": [
            "Mod+Shift+E"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "git",
    "title": "Source Control",
    "description": "Stage, commit, fetch/pull/push and generate AI commit messages; shows ahead/behind in the sidebar.",
    "tier": "recommended",
    "icon": "git-commit",
    "category": "Workbench",
    "requires": [
      "diff-viewer"
    ],
    "contributes": {
      "leftPanels": [
        "git"
      ],
      "commands": [
        {
          "id": "view.git",
          "title": "Toggle Git Panel",
          "category": "View",
          "keys": [
            "Mod+Shift+G"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "jev",
    "title": "Jev",
    "description": "Typed yes/no, choice and score decisions from TypeSafe's Jev model. Suggests the right moment to compact the context (task boundaries, cold prompt cache) and gives the agent an ask_jev tool. Paste your TypeSafe API key in Settings → AI Providers.",
    "tier": "bonus",
    "recommended": false,
    "icon": "gauge",
    "category": "AI",
    "contributes": {
      "tabKinds": [
        "jev-insights"
      ]
    },
    "agent": {
      "extensions": [
        "agent/extensions/jev.ts"
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "library",
    "title": "Skills & Agents Library",
    "description": "Browse, inspect, and configure your coding agent skills, system prompts, and custom subagents with a dedicated editor.",
    "tier": "bonus",
    "icon": "blocks",
    "category": "Agent",
    "contributes": {
      "tabKinds": [
        "library"
      ],
      "commands": [
        {
          "id": "view.library",
          "title": "Open Skills & Agents",
          "category": "View",
          "keys": [
            "Mod+Shift+K"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "limits",
    "title": "Live limits",
    "description": "Status-bar meters and a hover popover showing your 5-hour and weekly subscription limits for Claude, Codex and Antigravity.",
    "tier": "recommended",
    "icon": "gauge",
    "category": "Agent",
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "marketplace",
    "title": "Marketplace",
    "description": "Browse and discover MCP servers, Pi extensions, and agent skills from npm, Anthropic, and the official MCP registry.",
    "tier": "bonus",
    "icon": "shopping-bag",
    "category": "Workbench",
    "contributes": {
      "rightPanels": [
        "marketplace"
      ],
      "commands": [
        {
          "id": "view.marketplace",
          "title": "Toggle Marketplace Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "plan-previewer",
    "title": "Plan Previewer",
    "description": "Review agent plans in a rich tab: decisions, questions, annotations and approve / request changes. Runs a local server on :3456 for the plan-previewer CLI and installs its Pi skills.",
    "tier": "recommended",
    "icon": "clipboard-check",
    "category": "Agent",
    "agent": {
      "skills": [
        "agent/skills/*"
      ],
      "agentsMd": "agent/AGENTS.block.md",
      "bin": {
        "plan-previewer": "bin/plan-previewer.js"
      }
    },
    "contributes": {
      "tabKinds": [
        "plan"
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "terminal",
    "title": "Terminal",
    "description": "Integrated terminal in the right panel (PowerShell / bash / zsh) rooted at your project folder.",
    "tier": "recommended",
    "icon": "terminal",
    "category": "Workbench",
    "contributes": {
      "rightPanels": [
        "terminal"
      ],
      "commands": [
        {
          "id": "view.terminal",
          "title": "Toggle Terminal Panel",
          "category": "View",
          "keys": [
            "Mod+`"
          ]
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  },
  {
    "id": "theme-studio",
    "title": "Arc Theme Studio",
    "description": "Interactive color pad, grain texture, gradient styling, custom color presets, and real-time palette tuner.",
    "tier": "bonus",
    "icon": "palette",
    "category": "Appearance",
    "hasMain": false,
    "hasRenderer": true
  },
  {
    "id": "tools",
    "title": "Tools Inspector",
    "description": "Inspect skills, subagents, MCP servers, and tools used by the active session with one-click jump to tool calls.",
    "tier": "bonus",
    "icon": "wrench",
    "category": "Workbench",
    "contributes": {
      "rightPanels": [
        "tools"
      ],
      "commands": [
        {
          "id": "view.tools",
          "title": "Toggle Tools Panel",
          "category": "View"
        }
      ]
    },
    "hasMain": true,
    "hasRenderer": true
  }
];

/** Lazy entry points; only called for enabled modules. */
export const MAIN_MODULE_LOADERS: Readonly<Record<string, () => Promise<{ default: MainModule }>>> = {
  "actions": () => import("@hive-module/actions/main"),
  "analytics": () => import("@hive-module/analytics/main"),
  "bash-guard": () => import("@hive-module/bash-guard/main"),
  "browser": () => import("@hive-module/browser/main"),
  "files": () => import("@hive-module/files/main"),
  "git": () => import("@hive-module/git/main"),
  "jev": () => import("@hive-module/jev/main"),
  "library": () => import("@hive-module/library/main"),
  "limits": () => import("@hive-module/limits/main"),
  "marketplace": () => import("@hive-module/marketplace/main"),
  "plan-previewer": () => import("@hive-module/plan-previewer/main"),
  "terminal": () => import("@hive-module/terminal/main"),
  "tools": () => import("@hive-module/tools/main"),
};
