/**
 * Pi CLI Extension: Destructive Bash Command Guard
 *
 * Intercepts tool_call events for `bash`. If a command matches a danger rule
 * (recursive deletion, destructive git, disk operations, elevated privileges,
 * pipe-to-shell, secret exfiltration, ...), it pauses execution and asks for approval.
 *
 * In Hive Studio the approval is an inline card above the composer (the confirm
 * body is a JSON `dangerous_bash_approval` payload, see src/shared.ts).
 * In headless mode (no UI) a flagged command is blocked.
 *
 * Optional Jev tier (off by default): with JEV_GUARD_ENABLED=1 and a key, commands the
 * rules did not recognise (and that are not on the read-only allowlist) are redacted and
 * sent to Jev for a risk opinion. Jev can only escalate to a confirm prompt; any failure
 * allows the command (fail-open).
 *
 * This file is the bundling entry for agent/extensions/bash-guard.ts, which is GENERATED by
 * scripts/build-extension.mjs: only `import type` from the Pi package may be used outside
 * src/engine and src/jev.ts, because Pi copies the generated file verbatim.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { analyzeCommand } from "../engine/analyze.ts";
import { decideFromJev, shouldJudge } from "../engine/judge.ts";
import { askJev, readJevConfig } from "../jev.ts";

interface Flag {
  severity: "critical" | "high" | "moderate";
  ruleId: string;
  ruleTitle: string;
  reason: string;
  matchedSegment: string;
}

export default function bashGuard(pi: ExtensionAPI): void {
  pi.on("tool_call", async (event, ctx) => {
    if (event.toolName !== "bash") return undefined;

    const command = (event.input as { command?: string })?.command ?? "";
    if (!command.trim()) return undefined;

    let flag: Flag | null = null;
    const hit = analyzeCommand(command);
    if (hit) {
      flag = { severity: hit.severity, ruleId: hit.id, ruleTitle: hit.title, reason: hit.reason, matchedSegment: hit.matchedSegment };
    } else if (readJevConfig().enabled && shouldJudge(command, false)) {
      // Jev tier: unknown command, opt-in only. Never throws; null = unreachable -> allow and log.
      const answers = await askJev(command, { log: (m) => console.error(m) });
      const verdict = decideFromJev(answers);
      if (verdict.confirm) {
        flag = { severity: verdict.severity, ruleId: "jev-judge", ruleTitle: "Flagged by Jev risk assessment", reason: verdict.reason, matchedSegment: command };
      }
    }
    if (!flag) return undefined;

    const payload = JSON.stringify({
      kind: "dangerous_bash_approval",
      command,
      severity: flag.severity,
      ruleId: flag.ruleId,
      ruleTitle: flag.ruleTitle,
      reason: flag.reason,
      matchedSegment: flag.matchedSegment,
    });

    if (!ctx.hasUI) {
      return {
        block: true,
        reason: `Destructive bash command blocked automatically in headless mode: ${flag.reason} (${command})`,
      };
    }

    const title = `⚠️ Dangerous Bash Command: ${flag.ruleTitle}`;
    const confirmed = await ctx.ui.confirm(title, payload);

    if (!confirmed) {
      return {
        block: true,
        reason: `Command execution blocked by user: ${flag.reason}`,
      };
    }

    return undefined;
  });
}
